#!/bin/sh

# Resource Impl: https://concourse-ci.org/implementing-resource-types.html
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 </full/path/to/dir>"
  exit 1
fi
#######################################

# parse incoming config data
payload=`cat`
bucket=$(echo "$payload" | jq -r '.source.bucket')
moveto=$(echo "$payload" | jq -r '.source.moveto // "building"')
archive=$(echo "$payload" | jq -r '.source.archive // "finished"')
outpath=$(echo "$payload" | jq -r '.source.outpath // ""')
options=$(echo "$payload" | jq -r '.source.options // [] | join(" ")')

# export for `aws` cli
AWS_ACCESS_KEY_ID=$(echo "$payload" | jq -r '.source.access_key_id // empty')
AWS_SECRET_ACCESS_KEY=$(echo "$payload" | jq -r '.source.secret_access_key // empty')
AWS_DEFAULT_REGION=$(echo "$payload" | jq -r '.source.region // empty')

# Due to precedence rules, must be unset to support AWS IAM Roles.
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
fi

# Export AWS_DEFAULT_REGION if set
[ -n "$AWS_DEFAULT_REGION" ] && export AWS_DEFAULT_REGION

cd $source/$outpath

echo "Moving files from S3 to S3..."
for element in `ls .`
do
    eval aws s3 mv "s3://$bucket/$moveto/$element" "s3://$bucket/$archive/$element"
done
echo "...done."

source "$(dirname $0)/emit.sh" >&3
